import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "ProFinish Solutions ATL",
  // TO DO: Update eventually.
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <nav>Nav 1</nav>
      <nav>Nav 2</nav>
        {children}
      </body>
    </html>
  );
}
